imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: services.yml }

# Configuración general del framework
framework:
    esi:             { enabled: true }
    translator:      { fallback: es }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Configuración de Twig
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        ciudad_por_defecto:  %cupon.ciudad_por_defecto%

# Configuración de Assetic
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: \.css$
        yui_js:
            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: \.js$
        
#        optipng:
#            bin: /usr/local/bin/optipng
#
#    twig:
#        functions:
#            optipng: ~

# Configuración de Doctrine
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:                true

# Configuración de Swiftmailer
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#    delivery_address:  javier.eguiluz@gmail.com

# Configuración del bundle JMS\SecurityExtraBundle
jms_security_extra:
    secure_controllers:  false
    secure_all_services: false

# Parámetros globales del contenedor de dependencias
parameters:
    cupon.ciudad_por_defecto:  'barcelona'
    cupon.directorio.imagenes: %kernel.root_dir%/../web/uploads/images/
