imports:
    - { resource: config.yml }

# Comenta las siguientes líneas si no tienes APC instalado en el
# servidor de producción
doctrine:
    orm:
        metadata_cache_driver: apc
        query_cache_driver:    apc
        result_cache_driver:   apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
